#!/usr/bin/env bash
#
# rotate-media-webdav.sh — rotate WebDAV auth in 1Password (Login item: MediaServer).
# Optionally syncs the optional local fallback file and legacy 1Password document backup.
#
# SECURITY: Never logs passwords. Requires an interactive 1Password CLI session (op signin).
# Trust boundary: 1Password vault + local ~/.config/media-server/credentials (if synced).
#
set -euo pipefail

OP_VAULT="${OP_VAULT:-Personal}"
OP_ITEM="${OP_ITEM:-MediaServer}"
LEGACY_DOC_TITLE="${LEGACY_DOC_TITLE:-Media Server WebDAV Credentials}"
CREDS_FILE="${MEDIA_CREDENTIALS_FILE:-$HOME/.config/media-server/credentials}"
PASSWORD_RECIPE="${PASSWORD_RECIPE:-letters,digits,32}"
LAUNCHD_LABEL="${MEDIA_WEBDAV_LAUNCHD_LABEL:-com.speedybee.media.server}"

DRY_RUN=false
SYNC_FILE_MODE="auto" # auto | always | never
SYNC_LEGACY_DOC=false
RESTART_SERVICE=false

usage() {
	cat <<'EOF'
Usage: rotate-media-webdav.sh [options]

Rotate the WebDAV password in 1Password (Login item "MediaServer" in vault "Personal")
and optionally refresh local fallback / legacy document backups.

Options:
  --dry-run              Preview 1Password changes without applying them
  --sync-file            Always write ~/.config/media-server/credentials (mode 600)
  --no-sync-file         Do not touch the local credentials file
  --sync-legacy-document Also update the "Media Server WebDAV Credentials" document item
  --restart-media        Restart LaunchAgent com.speedybee.media.server (macOS only)
  -h, --help             Show this help

Environment overrides:
  OP_VAULT, OP_ITEM, LEGACY_DOC_TITLE, MEDIA_CREDENTIALS_FILE,
  PASSWORD_RECIPE, MEDIA_WEBDAV_LAUNCHD_LABEL

After rotation, update Infuse / other WebDAV clients with the new password from 1Password.
EOF
}

log() {
	printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

require_op() {
	if ! command -v op &>/dev/null; then
		log "ERROR: 1Password CLI (op) is not installed."
		log "Install: https://developer.1password.com/docs/cli/get-started/"
		exit 1
	fi
	if ! op account list &>/dev/null; then
		log "ERROR: Not signed in to 1Password CLI. Run: eval \"\$(op signin)\""
		exit 1
	fi
}

op_item_exists() {
	op item get "$OP_ITEM" --vault "$OP_VAULT" --format json &>/dev/null
}

read_username() {
	op read "op://$OP_VAULT/$OP_ITEM/username"
}

read_password() {
	op read "op://$OP_VAULT/$OP_ITEM/password"
}

rotate_in_1password() {
	local -a cmd=(op item edit "$OP_ITEM" --vault "$OP_VAULT" "--generate-password=$PASSWORD_RECIPE")
	if $DRY_RUN; then
		cmd+=(--dry-run)
	fi
	log "Rotating password in 1Password item '$OP_ITEM' (vault: $OP_VAULT)..."
	"${cmd[@]}"
}

write_credentials_file() {
	local web_user="$1"
	local web_pass="$2"
	local creds_dir
	creds_dir=$(dirname "$CREDS_FILE")
	mkdir -p "$creds_dir"
	umask 077
	{
		printf '%s\n' "# Generated by rotate-media-webdav.sh — do not commit"
		printf "MEDIA_WEBDAV_USER='%s'\n" "$web_user"
		printf "MEDIA_WEBDAV_PASS='%s'\n" "$web_pass"
	} >"$CREDS_FILE"
	chmod 600 "$CREDS_FILE"
	log "Wrote fallback credentials file: $CREDS_FILE (mode 600)"
}

sync_legacy_document() {
	local web_user="$1"
	local web_pass="$2"
	local tmp
	tmp=$(mktemp)
	chmod 600 "$tmp"
	# shellcheck disable=SC2064
	trap 'rm -f "$tmp"' RETURN
	{
		printf "MEDIA_WEBDAV_USER='%s'\n" "$web_user"
		printf "MEDIA_WEBDAV_PASS='%s'\n" "$web_pass"
	} >"$tmp"
	log "Updating legacy 1Password document: $LEGACY_DOC_TITLE"
	if $DRY_RUN; then
		log "(dry-run) Would run: op document edit \"$LEGACY_DOC_TITLE\" <tmp> --vault $OP_VAULT"
		return 0
	fi
	op document edit "$LEGACY_DOC_TITLE" "$tmp" --vault "$OP_VAULT"
}

should_sync_file() {
	case "$SYNC_FILE_MODE" in
	always) return 0 ;;
	never) return 1 ;;
	auto)
		if [[ -f $CREDS_FILE ]]; then
			return 0
		fi
		return 1
		;;
	*)
		log "ERROR: invalid SYNC_FILE_MODE: $SYNC_FILE_MODE"
		exit 1
		;;
	esac
}

restart_media_launchagent() {
	if [[ $(uname -s) != Darwin ]]; then
		log "Skipping LaunchAgent restart (not macOS)."
		return 0
	fi
	if $DRY_RUN; then
		log "(dry-run) Would restart LaunchAgent: $LAUNCHD_LABEL"
		return 0
	fi
	local uid domain target
	uid=$(id -u)
	domain="gui/$uid"
	target="$domain/$LAUNCHD_LABEL"
	if launchctl print "$target" &>/dev/null; then
		log "Restarting LaunchAgent: $target"
		launchctl kickstart -k "$target"
	else
		log "WARNING: LaunchAgent not loaded ($target). Start manually if needed."
	fi
}

print_post_rotation_checklist() {
	cat <<EOF

Post-rotation checklist:
  1. Confirm 1Password item '$OP_ITEM' shows a new password (1Password app).
  2. Update Infuse / other WebDAV clients (old password no longer works).
  3. Verify locally: curl -u "USER:\$(op read op://$OP_VAULT/$OP_ITEM/password)" http://127.0.0.1:8080/
     (adjust port if your daemon binds elsewhere)
  4. If remote access is enabled, confirm Windscribe port-forward still matches your WebDAV port.

EOF
}

while [[ $# -gt 0 ]]; do
	case "$1" in
	--dry-run)
		DRY_RUN=true
		shift
		;;
	--sync-file)
		SYNC_FILE_MODE=always
		shift
		;;
	--no-sync-file)
		SYNC_FILE_MODE=never
		shift
		;;
	--sync-legacy-document)
		SYNC_LEGACY_DOC=true
		shift
		;;
	--restart-media)
		RESTART_SERVICE=true
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		log "ERROR: Unknown option: $1"
		usage
		exit 1
		;;
	esac
done

require_op

if ! op_item_exists; then
	log "ERROR: 1Password item '$OP_ITEM' not found in vault '$OP_VAULT'."
	log "Create a Login item named '$OP_ITEM' with username/password fields, or set OP_ITEM / OP_VAULT."
	exit 1
fi

web_user=$(read_username)
if [[ -z $web_user ]]; then
	log "ERROR: Could not read username from op://$OP_VAULT/$OP_ITEM/username"
	exit 1
fi

rotate_in_1password

if $DRY_RUN; then
	log "Dry run complete. No password read or local files written."
	print_post_rotation_checklist
	exit 0
fi

web_pass=$(read_password)
if [[ -z $web_pass ]]; then
	log "ERROR: Password rotation succeeded but op read returned empty password."
	exit 1
fi

if should_sync_file; then
	write_credentials_file "$web_user" "$web_pass"
fi

if $SYNC_LEGACY_DOC; then
	sync_legacy_document "$web_user" "$web_pass"
fi

if $RESTART_SERVICE; then
	restart_media_launchagent
fi

log "WebDAV password rotation complete for user: $web_user"
print_post_rotation_checklist
