name: CodeScene PR Refactoring Agent Test

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  refactor:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/cs-agent')
    runs-on: ubuntu-latest
    steps:
      - name: Prepare command
        id: prepare-command
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          echo "COMMENT_BODY=$COMMENT_BODY"
          echo "test"